# 20260729-1210_017
[nginx_linux]
54.252.39.1 ansible_user=ec2-user ansible_ssh_private_key_file=../terraform/hantt-practical-key.pem

[nginx_linux:vars]
ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new

[nginx_windows]
54.252.194.95 ansible_user=Administrator ansible_password="{{ lookup('env', 'WIN_ADMIN_PASS') }}"

[nginx_windows:vars]
ansible_connection=winrm
ansible_port=5985
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore
